sudo: required
services:
  - docker

before_install:
  - sudo apt-get install apache2-utils # provides the benchmark tool

  - docker pull bryanlatten/docker-php:7.1
  - docker pull litaio/redis:latest

  - docker build -t test_image .

  - docker run -d --name redis litaio/redis
  - docker run -e CFG_APP_DEBUG=0 --link redis:redis -d -p 80:8080 test_image

script:
  - ./benchmark.sh
